### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [Eblohm/project10#1]
I'm getting an error when trying to create a new baseball stat. :cry:

**Comment by Eblohm** [comment]
Just pushed a fix for that! I'll also update the other issues you pointed out from Project9 once I get them all figured out.

**Comment by chrisvfritz** [comment]
Did you also push this to Heroku? When I [visit this page](https://salty-citadel-9562.herokuapp.com/baseballstats/new) and just click `Create Baseballstat`, I'm still getting that error.

**Comment by Eblohm** [comment]
Oops! Pushed the fix to heroku! It should work now.

**Comment by chrisvfritz** [comment]
:+1: Much better!
